name: "Blacklock Code Scanner"
description: "Scans code with Semgrep and Trivy, and uploads issues to SonarQube."
author: "My Company"

inputs:
  sonar_projectkey:
    description: "SonarQube Project Key"
    required: true
  sonar_host_url:
    description: "SonarQube Host URL"
    required: true
  sonar_token:
    description: "SonarQube Token"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    SONAR_PROJECTKEY: ${{ inputs.sonar_projectkey }}
    SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
    SONAR_TOKEN: ${{ inputs.sonar_token }}

branding:
  icon: "shield"
  color: "blue"
