name: "Blacklock Code Scanner Action"
description: "A GitHub Action that runs Blacklock Code Scanner via Docker"
author: "My Company"

inputs:
  sonar_projectkey:
    description: "SonarQube Project Key"
    required: true
  sonar_host_url:
    description: "SonarQube Host URL"
    required: true
  sonar_token:
    description: "SonarQube Token"
    required: true
  exclude:
    description: "Comma-separated list of paths to exclude from the scan"
    required: false
    default: ""  # Default to no exclusions

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--sonar_projectkey"
    - "${{ inputs.sonar_projectkey }}"
    - "--sonar_host_url"
    - "${{ inputs.sonar_host_url }}"
    - "--sonar_token"
    - "${{ inputs.sonar_token }}"
    - "--exclude"
    - "${{ inputs.exclude }}"  # Pass the exclude parameter

branding:
  icon: "shield"
  color: "blue"
