name: "My Professional GitHub Action"
description: "A GitHub Action that reads blacklock.yml and performs tasks securely"
author: "My Company"

inputs:
  param1:
    description: "First parameter"
    required: true
    default: "default-value"
  param2:
    description: "Second parameter"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"  # GitHub will use this Dockerfile to build the image
  args:
    - "${{ inputs.param1 }}"
    - "${{ inputs.param2 }}"

branding:
  icon: "terminal"
  color: "blue"
